services:
  # A Docker web service
  - type: web
    name: notes-app
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: poetry install
    startCommand: uvicorn main:app --chdir ./notes_app --host 0.0.0.0 --port $PORT